export const PAKISTAN_CITIES = [
  "Abbottabad",
  "Arifwala",
  "Attock",
  "Badin",
  "Bahawalnagar",
  "Bahawalpur",
  "Bannu",
  "Batkhela",
  "Bhakkar",
  "Bhalwal",
  "Burewala",
  "Chakwal",
  "Charsadda",
  "Chiniot",
  "Dadu",
  "Daska",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Gilgit",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Gwadar",
  "Hafizabad",
  "Haripur",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Kamalia",
  "Kamoke",
  "Karachi",
  "Kasur",
  "Khanewal",
  "Khanpur",
  "Khairpur",
  "Khuzdar",
  "Kohat",
  "Kot Addu",
  "Lahore",
  "Larkana",
  "Mandi Bahauddin",
  "Mardan",
  "Mianwali",
  "Mingora",
  "Mirpur Khas",
  "Multan",
  "Muzaffarabad",
  "Muzaffargarh",
  "Narowal",
  "Nawabshah",
  "Nowshera",
  "Okara",
  "Pakpattan",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sadiqabad",
  "Sahiwal",
  "Sargodha",
  "Shahdadkot",
  "Sheikhupura",
  "Shikarpur",
  "Sialkot",
  "Sukkur",
  "Swabi",
  "Tando Adam",
  "Taxila",
  "Toba Tek Singh",
  "Vehari",
  "Wah Cantonment",
  "Wazirabad",
] as const;

export const SWEDEN_CITIES = [
  "Alingsas",
  "Angelholm",
  "Boras",
  "Eskilstuna",
  "Falun",
  "Gavle",
  "Gothenburg",
  "Halmstad",
  "Hassleholm",
  "Helsingborg",
  "Hudiksvall",
  "Jonkoping",
  "Kalmar",
  "Karlskrona",
  "Karlstad",
  "Kristianstad",
  "Kungsbacka",
  "Landskrona",
  "Linkoping",
  "Lulea",
  "Lund",
  "Malmo",
  "Molndal",
  "Nacka",
  "Norrkoping",
  "Orebro",
  "Ornskoldsvik",
  "Skelleftea",
  "Sodertalje",
  "Stockholm",
  "Sundsvall",
  "Trelleborg",
  "Trollhattan",
  "Uddevalla",
  "Umea",
  "Uppsala",
  "Varberg",
  "Vasteras",
  "Vaxjo",
  "Visby",
  "Ystad",
  "Ostersund",
] as const;
